# Generated by Django 5.0.2 on 2024-02-23 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 23, 10, 42, 29, 334773, tzinfo=datetime.timezone.utc)),
        ),
    ]
